### ISSUE TITLE
Create patch releases for latest bug fixes

### ISSUE THREAD

**Issue by MatthiasWerning** [kubernetes-sigs/sig-storage-lib-external-provisioner#163]
Hello, as referenced in #162 it would be very helpful to have new patch releases which include the latest context cancellation fix. There has been no release since July last year. I think the community would really welcome a new release tag.

**Comment by niranjandarshann** [comment]
As referenced in issue #162, it would be very helpful to have new patch releases that include the latest context cancellation fix. There has been no release since July last year, and I believe the community would greatly appreciate a new release tag. Regular updates ensure that we benefit from the latest fixes and improvements, enhancing the stability and reliability of our projects.

Thank You for Bringing this to the community attention.
