### ISSUE TITLE
Volume expansion support?

### ISSUE THREAD

**Issue by fengye87** [kubernetes-sigs/sig-storage-lib-external-provisioner#43]
Any plan to support volume expansion?

**Comment by wongma7** [comment]
No, you'll have to write a CSI driver. https://github.com/NetApp/trident has a resize controller somewhere but I don't think it's in library form.

**Comment by candlerb** [comment]
May I ask: is there is a fundamental reason why an external provisioner could not watch PVCs and resize PVs?  Or is it just lack of time to implement in sig-storage-lib-external-provisioner?

The [volume provisioning](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/storage/volume-provisioning.md) document doesn't mention growing volumes.  It does however talk about some other new features, e.g. raw block devices.

**Comment by wongma7** [comment]
The main reason is I want to steer developers to CSI and I don't want to duplicate the efforts of CSI.

Have a look at https://github.com/kubernetes-csi/external-resizer.

Technically it should be possible to consume the pkg/controller at https://github.com/kubernetes-csi/external-resizer/tree/master/pkg/controller by implementing the Resizer interface at https://github.com/kubernetes-csi/external-resizer/blob/master/pkg/resizer/resizer.go#L24, the same way you consume the sig-storage-lib-external-provisioner controller by implementing the Provisioner interface.

It will probably be more difficult since external-resizer is not intended to be a library and sig-storage-lib-external-provisioner obviously is, but it should be possible with some golang dependency management magic.

To make it easier, external-resizer could be refactored to consume a new sig-storage-lib-external-resizer, the same way external-provisioner consumes this sig-storage-lib-external-provisioner. But I don't think there is currently any intention of doing that and there are certainly drawbacks to that (repo sprawl, dependency management, coupling of external-* to sig-torage-lib-external-*)

Anyway, I would create an issue at https://github.com/kubernetes-csi/external-resizer if you would like to discuss this further. CSI is priority 0 for sig-storage but certainly they shouldn't forget about people who want to write traditional PVC/PV controllers

**Comment by candlerb** [comment]
> The main reason is I want to steer developers to CSI and I don't want to duplicate the efforts of CSI.

Understood, thank you.

The reason is I have been using the [local-zfs-provisioner](https://github.com/asteven/local-zfs-provisioner) which uses the external volume provisioner interface to create a zfs dataset of the requested size.  I was wondering whether it would be possible to extend it to support growing volumes - which at the backend is as simple as updating the "quota" parameter on the dataset.

It seems it may not be as straightforward as I thought.  But rewriting it to use CSI for both provisioning and resizing could also be a lot of work (although might have other benefits, such as supporting snapshotting)
