### ISSUE TITLE
ServiceAccount for provisioner requires "update" verb on "endpoint" resources

### ISSUE THREAD

**Issue by rajch** [kubernetes-sigs/sig-storage-lib-external-provisioner#49]
In the past, I have seen provisioners run successfully with a ServiceAccount bound to either of the following two ClusterRoles:
- system:persistent-volume-provisioner
- system:controller:persistent-volume-binder

However, the controller seems to want permissions to the "update" verb on "endpoint" resources, which neither of the above provide. I solved my problem by creating a custom ClusterRole. This may not be a bug, but could we add it to documentation somewhere?

**Comment by wongma7** [comment]
Yes, RBAC requirements need to be documented and versioned. The controller used to use PVC's as locks but now it uses endpoints. There is a TODO to default to Leases instead since touching endpoints can have security & performance issues. You can disable leader election altogether, it's mainly to avoid controllers racing and hitting Provision API unnecessarily
/assign

**Comment by rajch** [comment]
/remove-lfecycle stale

May I volunteer to (as a stopgap) update the README with RBAC requirements?
